"""
ForensAI - Investigator Notes Manager
======================================
Manages investigator notes and AI-generated explanations for artifacts.

Notes are stored in SQLite and can be:
- Generated by AI or written manually
- Edited before inclusion in reports
- Exported to various formats
- Linked to specific artifacts (files, registry keys, carved data)
"""

import sqlite3
import json
from datetime import datetime
from typing import List, Dict, Optional
from pathlib import Path


class Note:
    """Represents a single investigator note."""

    def __init__(self, note_id: int = None, artifact_type: str = None,
                 artifact_id: str = None, artifact_name: str = None,
                 content: str = None, ai_generated: bool = False,
                 edited: bool = False, timestamp: str = None,
                 tags: List[str] = None):
        """
        Initialize note.

        Args:
            note_id: Unique note ID
            artifact_type: Type of artifact ('file', 'registry', 'carved', 'timeline')
            artifact_id: Unique identifier (inode+offset, registry path, etc.)
            artifact_name: Human-readable name
            content: Note text
            ai_generated: Whether generated by AI
            edited: Whether AI-generated note was edited
            timestamp: Creation timestamp
            tags: Optional tags for categorization
        """
        self.note_id = note_id
        self.artifact_type = artifact_type
        self.artifact_id = artifact_id
        self.artifact_name = artifact_name
        self.content = content
        self.ai_generated = ai_generated
        self.edited = edited
        self.timestamp = timestamp or datetime.now().isoformat()
        self.tags = tags or []

    def to_dict(self) -> Dict:
        """Convert to dictionary."""
        return {
            'note_id': self.note_id,
            'artifact_type': self.artifact_type,
            'artifact_id': self.artifact_id,
            'artifact_name': self.artifact_name,
            'content': self.content,
            'ai_generated': self.ai_generated,
            'edited': self.edited,
            'timestamp': self.timestamp,
            'tags': self.tags
        }


class NotesManager:
    """Manages investigator notes database."""

    def __init__(self, db_path: str = "data/notes.db"):
        """
        Initialize notes manager.

        Args:
            db_path: Path to SQLite database file
        """
        self.db_path = db_path

        # Ensure directory exists
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)

        # Initialize database
        self._init_database()

    def _init_database(self):
        """Create database tables if they don't exist."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Notes table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS notes (
                note_id INTEGER PRIMARY KEY AUTOINCREMENT,
                artifact_type TEXT NOT NULL,
                artifact_id TEXT NOT NULL,
                artifact_name TEXT,
                content TEXT NOT NULL,
                ai_generated INTEGER DEFAULT 0,
                edited INTEGER DEFAULT 0,
                timestamp TEXT NOT NULL,
                tags TEXT,
                UNIQUE(artifact_type, artifact_id)
            )
        ''')

        # Index for faster lookups
        cursor.execute('''
            CREATE INDEX IF NOT EXISTS idx_artifact
            ON notes(artifact_type, artifact_id)
        ''')

        conn.commit()
        conn.close()

    def add_note(self, note: Note) -> int:
        """
        Add or update a note.

        Args:
            note: Note object to add

        Returns:
            Note ID
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        try:
            # Check if note exists for this artifact
            existing = self.get_note_for_artifact(note.artifact_type, note.artifact_id)

            if existing:
                # Update existing note
                cursor.execute('''
                    UPDATE notes
                    SET content = ?, edited = ?, timestamp = ?, tags = ?
                    WHERE artifact_type = ? AND artifact_id = ?
                ''', (
                    note.content,
                    1 if note.ai_generated else 0,  # Mark as edited if updating AI note
                    datetime.now().isoformat(),
                    json.dumps(note.tags),
                    note.artifact_type,
                    note.artifact_id
                ))
                note_id = existing.note_id
            else:
                # Insert new note
                cursor.execute('''
                    INSERT INTO notes
                    (artifact_type, artifact_id, artifact_name, content,
                     ai_generated, edited, timestamp, tags)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                ''', (
                    note.artifact_type,
                    note.artifact_id,
                    note.artifact_name,
                    note.content,
                    1 if note.ai_generated else 0,
                    1 if note.edited else 0,
                    note.timestamp,
                    json.dumps(note.tags)
                ))
                note_id = cursor.lastrowid

            conn.commit()
            return note_id

        finally:
            conn.close()

    def get_note_for_artifact(self, artifact_type: str, artifact_id: str) -> Optional[Note]:
        """
        Get note for a specific artifact.

        Args:
            artifact_type: Type of artifact
            artifact_id: Artifact identifier

        Returns:
            Note object or None if not found
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute('''
            SELECT note_id, artifact_type, artifact_id, artifact_name,
                   content, ai_generated, edited, timestamp, tags
            FROM notes
            WHERE artifact_type = ? AND artifact_id = ?
        ''', (artifact_type, artifact_id))

        row = cursor.fetchone()
        conn.close()

        if row:
            return Note(
                note_id=row[0],
                artifact_type=row[1],
                artifact_id=row[2],
                artifact_name=row[3],
                content=row[4],
                ai_generated=bool(row[5]),
                edited=bool(row[6]),
                timestamp=row[7],
                tags=json.loads(row[8]) if row[8] else []
            )
        return None

    def get_all_notes(self, artifact_type: str = None) -> List[Note]:
        """
        Get all notes, optionally filtered by type.

        Args:
            artifact_type: Optional filter by artifact type

        Returns:
            List of Note objects
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        if artifact_type:
            cursor.execute('''
                SELECT note_id, artifact_type, artifact_id, artifact_name,
                       content, ai_generated, edited, timestamp, tags
                FROM notes
                WHERE artifact_type = ?
                ORDER BY timestamp DESC
            ''', (artifact_type,))
        else:
            cursor.execute('''
                SELECT note_id, artifact_type, artifact_id, artifact_name,
                       content, ai_generated, edited, timestamp, tags
                FROM notes
                ORDER BY timestamp DESC
            ''')

        rows = cursor.fetchall()
        conn.close()

        notes = []
        for row in rows:
            notes.append(Note(
                note_id=row[0],
                artifact_type=row[1],
                artifact_id=row[2],
                artifact_name=row[3],
                content=row[4],
                ai_generated=bool(row[5]),
                edited=bool(row[6]),
                timestamp=row[7],
                tags=json.loads(row[8]) if row[8] else []
            ))

        return notes

    def delete_note(self, note_id: int) -> bool:
        """
        Delete a note.

        Args:
            note_id: ID of note to delete

        Returns:
            True if deleted, False if not found
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute('DELETE FROM notes WHERE note_id = ?', (note_id,))
        deleted = cursor.rowcount > 0

        conn.commit()
        conn.close()

        return deleted

    def clear_all_notes(self):
        """Delete all notes from database."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute('DELETE FROM notes')

        conn.commit()
        conn.close()

    def export_notes_to_dict(self) -> Dict[str, List[Dict]]:
        """
        Export all notes grouped by artifact type.

        Returns:
            Dictionary with artifact types as keys, lists of note dicts as values
        """
        notes = self.get_all_notes()

        exported = {
            'file': [],
            'registry': [],
            'carved': [],
            'timeline': [],
            'other': []
        }

        for note in notes:
            artifact_type = note.artifact_type if note.artifact_type in exported else 'other'
            exported[artifact_type].append(note.to_dict())

        return exported

    def get_notes_count(self) -> Dict[str, int]:
        """
        Get count of notes by type.

        Returns:
            Dictionary with counts
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute('''
            SELECT artifact_type, COUNT(*)
            FROM notes
            GROUP BY artifact_type
        ''')

        counts = dict(cursor.fetchall())
        conn.close()

        return counts


# Singleton instance
_notes_manager = None

def get_notes_manager() -> NotesManager:
    """Get singleton notes manager instance."""
    global _notes_manager
    if _notes_manager is None:
        _notes_manager = NotesManager()
    return _notes_manager
